# If there are words that you think should not be treated as typo.
# Please list here along with a comment.
[default.extend-words]
# Preserved for NdJson
"Nd" = "Nd"
# Microsoft K8s Server
"AKS" = "AKS"
# Wrong cases
"ba" = "ba"
"ue" = "ue"
"INOUT" = "INOUT"
"ser" = "ser"
"Ser" = "Ser"
"flate" = "flate"
"Tke" = "Tke"

[files]
extend-exclude = [
  "cli/frontend",
  "frontend"
]
