baseDir = "."

headerPath = "Apache-2.0.txt"

excludes = [
    # hidden files
    ".cargo",
    ".github",
    ".dockerignore",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".npmignore",
    ".prettierignore",

    "LICENSE",
    "Dockerfile",
    "Makefile",

    # docs and generated files
    "**/*.md",
    "**/*.hbs",
    "**/*.template",
    "**/*.cue",
    "**/*.json",
    "**/*.sql",
    "**/*.proto",
    "**/*.yml",
    "**/*.yaml",
    "**/*.toml",
    "**/*.lock",
    "**/*.yapf",
    "**/*.test",
    "**/*.txt",

    # test files
    "core/tests/**",
    "driver/tests/**",
    "cli/tests/**",

    # frontend files
    "frontend/**",
    "cli/frontend",
]

[properties]
inceptionYear = 2021
copyrightOwner = "Datafuse Labs"
