# .github/workflows/docker-publish.yml

name: TTC docker publish

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'core/**'
      - 'driver/**'
      - 'ttc/**'
      - 'sql/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag
        shell: bash
        run: |
          ref_v="${{ github.ref }}"
          if [[ $ref_v == refs/tags/* ]]; then
            DOCKER_TAG=${ref_v:10}
          else
            DOCKER_TAG="latest"
          fi
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - name: Print Docker tag
        shell: bash
        run: |
          echo "Start to build and publish: datafuselabs/ttc-rust:$DOCKER_TAG"

      - name: TTC Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./ttc/Dockerfile
          tags: datafuselabs/ttc-rust:${{ env.DOCKER_TAG }}
